package lab

func sitePresets() []Doc {
	baseCSS := `*{box-sizing:border-box}body{margin:0;font:14px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#24324a;background:#f4f6fa}header{height:64px;background:#fff;border-bottom:1px solid #e6eaf0;display:flex;align-items:center;padding:0 28px;gap:12px}header strong{font-size:22px;color:#1684df}header small{margin-left:auto;color:#8995a6}.layout{display:flex;min-height:calc(100vh - 64px)}aside{width:216px;background:#fff;padding:28px 20px;color:#66748b}aside div{padding:13px;margin-bottom:8px;border-radius:6px}.selected{background:#eaf4ff;color:#1478ce}main{flex:1;padding:30px;min-width:0}h1{font-size:22px;margin:0 0 8px}p{color:#7e8ba0}.card{background:#fff;border:1px solid #e4eaf1;border-radius:8px;padding:24px;margin-top:24px}.toolbar{display:flex;align-items:center;gap:12px;margin-bottom:24px}input{border:1px solid #dce3ec;border-radius:5px;padding:10px 12px;min-width:230px}button{border:0;border-radius:5px;background:#1684df;color:white;padding:10px 18px;cursor:pointer}table{border-collapse:collapse;width:100%;text-align:left}th{font-weight:500;color:#8390a4;background:#f8faff}td,th{padding:16px 12px;border-bottom:1px solid #edf0f4}td button{background:none;color:#1684df;padding:0}.pill{background:#e8f7ef;color:#219267;font-size:12px;padding:4px 8px;border-radius:4px}pre{background:#f5f8fc;padding:20px;white-space:pre-wrap;overflow-wrap:anywhere;min-height:90px;color:#41516a}.muted{font-size:12px;color:#9ba7b7}@media(max-width:700px){aside{display:none}main{padding:16px}.card{padding:14px}input{min-width:0;width:100%}.toolbar{flex-wrap:wrap}table{font-size:12px}td,th{padding:12px 5px}}`
	configHTML := `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>配置中心</title><link rel="stylesheet" href="assets/style.css"></head><body><header><strong>Configuration</strong><span>配置管理中心</span><small>public / 默认命名空间</small></header><div class="layout"><aside><div class="selected">配置管理</div><div>服务列表</div><div>命名空间</div><div>集群管理</div></aside><main><h1>配置列表</h1><p>集中管理应用配置与环境信息</p><section class="card"><div class="toolbar"><input id="query" placeholder="输入 Data ID 搜索"><button id="search">查询</button><span class="muted">共 1 项配置</span></div><table><thead><tr><th>Data ID</th><th>Group</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>application.yml</td><td>DEFAULT_GROUP</td><td><span class="pill">已发布</span></td><td><button data-config="application.yml">详情</button></td></tr></tbody></table></section><section class="card"><h3>配置内容</h3><pre id="output">选择配置查看详情。</pre></section></main></div><script src="assets/app.js"></script></body></html>`
	configJS := `const output=document.getElementById('output');async function load(id){output.textContent='正在读取配置…';try{const r=await fetch('/nacos/v1/cs/configs?dataId='+encodeURIComponent(id)+'&group=DEFAULT_GROUP');output.textContent=await r.text()}catch(e){output.textContent='配置服务暂不可用'}}document.querySelectorAll('[data-config]').forEach(b=>b.addEventListener('click',()=>load(b.dataset.config)));document.getElementById('search').addEventListener('click',async()=>{try{const r=await fetch('/nacos/v1/cs/configs?search=accurate&dataId='+encodeURIComponent(document.getElementById('query').value)+'&group=DEFAULT_GROUP');output.textContent=await r.text()}catch(e){output.textContent='配置服务暂不可用'}});`
	filesHTML := `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>团队文件中心</title><link rel="stylesheet" href="assets/style.css"></head><body><header><strong>Workspace</strong><span>团队文件中心</span><small>研发团队 / 共享空间</small></header><div class="layout"><aside><div class="selected">全部文件</div><div>最近访问</div><div>与我共享</div><div>回收站</div></aside><main><h1>共享文件</h1><p>项目文档、环境配置与运维资料</p><section class="card"><div class="toolbar"><input id="query" placeholder="输入文件名称"><button id="search">打开文件</button><span class="muted">团队共享目录</span></div><table><thead><tr><th>名称</th><th>类型</th><th>大小</th><th>操作</th></tr></thead><tbody><tr><td>README.md</td><td>Markdown</td><td>2.4 KB</td><td><button data-file="README.md">查看</button></td></tr></tbody></table></section><section class="card"><h3>文件预览</h3><pre id="output">选择文件查看内容。</pre></section></main></div><script src="assets/app.js"></script></body></html>`
	filesJS := `const output=document.getElementById('output');async function load(file){output.textContent='正在打开文件…';try{const r=await fetch('/api/download?file='+encodeURIComponent(file));output.textContent=await r.text()}catch(e){output.textContent='文件服务暂不可用'}}document.querySelectorAll('[data-file]').forEach(b=>b.addEventListener('click',()=>load(b.dataset.file)));document.getElementById('search').addEventListener('click',()=>load(document.getElementById('query').value||'README.md'));`
	makeSite := func(id, name, html, js string) Doc {
		return validateSite(Doc{"id": id, "name": name, "entry": "index.html", "version": 1, "spa": false, "source": "builtin", "files": []Doc{{"path": "index.html", "encoding": "utf8", "content": html}, {"path": "assets/style.css", "encoding": "utf8", "content": baseCSS}, {"path": "assets/app.js", "encoding": "utf8", "content": js}}})
	}
	return []Doc{makeSite("config-center", "配置中心（Nacos 风格）", configHTML, configJS), makeSite("file-center", "团队文件中心", filesHTML, filesJS)}
}
